### ISSUE TITLE
Newest stable flutter incompatible with ogurets

### ISSUE THREAD

**Issue by apuna12** [dart-ogurets/OguretsFlutter#11]
Hello again,

today we had to upgrade our flutter to version 1.22.2.

After upgrading and executing Pub Get I get this error

`Because no versions of ogurets_flutter match >1.2.7 <2.0.0 and ogurets_flutter 1.2.7 depends on flutter_driver any from sdk, ogurets_flutter ^1.2.7 requires flutter_driver any from sdk.
And because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2, ogurets_flutter ^1.2.7 requires platform 3.0.0-nullsafety.2.
And because firebase_messaging 6.0.16 depends on platform ^2.0.0 and no versions of firebase_messaging match >6.0.16 <7.0.0, ogurets_flutter ^1.2.7 is incompatible with firebase_messaging ^6.0.16.
So, because app depends on both firebase_messaging ^6.0.16 and ogurets_flutter ^1.2.7, version solving failed.
pub get failed (1; So, because app depends on both firebase_messaging ^6.0.16 and ogurets_flutter ^1.2.7, version solving failed.)`

I this case the code of pubspec.yaml is 

```
`version: 1.0.0+7

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^0.1.6
  rxdart: ^0.24.1
  http: any
  json_annotation: ^0.2.3
  json_serializable: ^0.5.0
  shared_preferences: ^0.5.2
  fluttertoast: ^4.0.0
  grouped_list: ^3.1.0
  intl: ^0.16.1
  calendar_time: ^1.0.1
  flutter_secure_storage: ^3.3.3
  video_player: ^0.10.11+2
  custom_navigator: ^0.3.0
  flutter_circular_chart: ^0.1.0
  open_file: ^3.0.1
  firebase_messaging: ^6.0.16
  connectivity: ^0.4.8+6
  data_connection_checker: ^0.3.4
  configurable_expansion_tile: ^1.0.0
  pie_chart: ^3.1.1
  charts_flutter: ^0.9.0
  gen_lang: ^0.1.3
  enum_to_string: ^1.0.9
  progress_dialog: ^1.2.4
  simple_tooltip: ^0.1.10
  flutter_clipboard_manager: ^0.0.2
  url_launcher: ^5.5.0
  flutter_email_sender: ^3.0.1
  flutter_html: ^1.0.0
  web_socket_channel: ^1.1.0
  tuple: ^1.0.3
  cryptoutils: ^0.4.0
  unorm_dart: ^0.1.2
  synchronized: ^2.2.0+2
  flutter_local_notifications: ^1.4.4+1
  collection: ^1.14.12
  cloud_firestore: ^0.14.0+2
  firebase_core: 0.5.0+1
  firebase_auth: ^0.18.0+2
  firebase_analytics: ^6.0.2
  uuid: 2.2.2
  badges: 1.1.1
  flushbar: ^1.10.4
  shimmer: ^1.1.2
  flutter_svg: ^0.18.0

  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.6.11

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  ogurets: ^3.2.0
  ogurets_flutter: ^1.2.7
`
```

After that I added `flutter_driver: sdk: flutter` into the `dev_dependencies:` , but I get the following error

```
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and firebase_messaging 6.0.16 depends on platform ^2.0.0, flutter_driver from sdk is incompatible with firebase_messaging 6.0.16.
And because no versions of firebase_messaging match >6.0.16 <7.0.0, flutter_driver from sdk is incompatible with firebase_messaging ^6.0.16.
So, because app depends on both firebase_messaging ^6.0.16 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because app depends on both firebase_messaging ^6.0.16 and flutter_driver any from sdk, version solving failed.)
```

This is flutter doctor output

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.16299.1127], locale en-US)
    • Flutter version 1.22.2 at C:\Projects\src\flutter
    • Framework revision 84f3d28555 (6 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.6
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
```

is there any possible solution for this?
